# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{exetel}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Kong"]
  s.date = %q{2010-05-10}
  s.description = %q{This gem wraps the SMS service provided by Exetel. You are required to have an Exetel account to use this service - http://www.exetel.com.au}
  s.email = %q{jkongie@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/exetel.rb",
     "lib/exetel/api.rb",
     "lib/exetel/api/command.rb",
     "lib/exetel/api/command_executor.rb",
     "lib/exetel/api/error.rb",
     "lib/exetel/api/message_status.rb",
     "lib/exetel/response.rb",
     "lib/exetel/response/type_keys.rb",
     "test/helper.rb",
     "test/test_exetel.rb"
  ]
  s.homepage = %q{http://github.com/jkongie/exetel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby API wrapper for the Exetel SMS Service}
  s.test_files = [
    "test/helper.rb",
     "test/test_exetel.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

